### ISSUE TITLE
EIPIP Meeting 112

### ISSUE THREAD

**Issue by poojaranjan** [ethcatherders/EIPIP#375]
# Meeting Info
- Date and Time: Jan 15, 2025 at 15:00 UTC 
- Zoom shared on the [ECH Discord #eip-editing](https://discord.gg/MFSunmfGxu) channel
- [EIPIP Meeting Recordings](https://www.youtube.com/playlist?list=PL4cwHXAawZxpLrRIkDlBjDUUrGgF91pQw)

# Agenda

### Edit to `Final` Proposals

- [x] https://github.com/ethereum/EIPs/pull/9226
- [x] https://github.com/ethereum/EIPs/pull/9186
- [x] https://github.com/ethereum/EIPs/pull/9199

### Update to EIP-1
- [x] https://github.com/ethereum/EIPs/pull/9151
- [x] https://github.com/ethereum/EIPs/pull/9153 (`Draft`)

### Other topics

- [x] https://github.com/ethereum/EIPs/pull/9174 (moved to discussion from Editing Office Hour)
- [x] can we have a tag that we can add to EIP: active consideration to prevent EIPs from being pulled in stagnent (or like have a 6monthly stangnant PR creation window than every now and then [Ref: Discord](https://discord.com/channels/916516304972824576/916713912970412103/1325499009749745676).

### Call for Input

Call For Input | Status | Inclination/Result | Deadline
-- | -- | -- | --
https://github.com/ethcatherders/EIPIP/issues/373 | Open | 1, In Favor | January 17th, 2025
https://github.com/ethcatherders/EIPIP/issues/374 | Open | 1, In Favor; 1 Unclear | January 17th, 2025
https://github.com/ethcatherders/EIPIP/issues/376 | Open | 1, Opposed | Feb 6th, 2025
https://github.com/ethcatherders/EIPIP/issues/367 | Closed | Rejected | Dec 04, 2024

## 2. Other discussions and updates from past meetings
- [x] Adding EIP Reviewers - permissions, requirements, roles & responsibilities
  - Reviewer's ref. [document](https://hackmd.io/@poojaranjan/EIPReviewer)
- [x] Adding new editors
   - [x] [Onboarding Checklist](https://hackmd.io/@poojaranjan/EIPEditorOnboarding)
   - [x] Formalize https://hackmd.io/@SamWilsn/B11QmJoq6 Ref. comments [here](https://github.com/ethcatherders/EIPIP/issues/365#issuecomment-2549891058) and [here](https://github.com/ethcatherders/EIPIP/issues/365#issuecomment-2550238682)
   - [x] Announcement - [EIP Editors' Workshop](https://github.com/ethcatherders/EIPIP/issues/372)

## 3. EIPs Insight - Monthly EIPs status reporting.
- [x] [January 2025](https://eipsinsight.com/insight/2021/1)
- [x] New tools demo Ref. [Comment](https://github.com/ethcatherders/EIPIP/issues/375#issuecomment-2592603953)
  - provide a demo of our new tool [Proposal Builder](https://eipsinsight.com/proposalbuilder)
  - RIPs page update [Link](https://eipsinsight.com/rip)
  - Search tool update [Link](https://eipsinsight.com/authors)
- [x] https://github.com/ethereum/EIPs/pull/9244

## 4. [EIP Editing Office Hour](https://hackmd.io/@poojaranjan/EIPEditingOfficeHour)
- Agenda [50](https://github.com/ethcatherders/EIPIP/issues/377) Video [49](https://youtube.com/live/isqaC0QKZ7M?feature=share)

## 5. Review action items from earlier meetings
- [x] [Notes 111](https://github.com/ethcatherders/EIPIP/issues/365#issuecomment-2552419992)
- [x] Add [EIPsInsight website link](https://eipsinsight.com/) to the [EIPs Website](https://eips.ethereum.org/).

## Next Meeting date & time - Feb 19, 2025 (3rd Wed of the Month) at 15:00 UTC?

**Comment by viwinkumarpadala** [comment]
Hello @poojaranjan , I would like share a few updates on the things that we discussed in the previous EIPIP meeting related to our website [EIPsInsight](https://eipsinsight.com/).

- provide a demo of our new tool [Proposal Builder](https://eipsinsight.com/proposalbuilder)
- RIPs page update [Link](https://eipsinsight.com/rip)
- Search tool update [Link](https://eipsinsight.com/authors)

**Comment by viwinkumarpadala** [comment]
Hello @poojaranjan we have also raised a pr on the EIPs github repository for adding our proposal builder tool to eips.ethereum.org header, Could you add it as well so that i can request the editors for considering that.

Link: [PR](https://github.com/ethereum/EIPs/pull/9244)

**Comment by poojaranjan** [comment]
## Summary
### 1. Discuss Open Issues/PRs, and other topics
#### Edit to Final Proposals
* Update EIP-7045: Update EIP-7045 ethereum/EIPs#9226
    * approved
* Update EIP-1485: Fix typographical errors in Documentation ethereum/EIPs#9186
    * **To do**: Sam will take a look at it. If just small typos, will be merged.
* Update EIP-101: Move to Draft ethereum/EIPs#9199
    * EIP-101 & EIP-4863 - Both proposals can not be brought back as we have passed the upgrade.
    * EIP-2565 is in `stagnant` which should not be receiving typo fixes.
    * Sam: This is removing the preamble, likly not going to be merged.
    * **To do**: Sam will leave a comment. 

#### Update to EIP-1
*  Update EIP-1: Add changes on top of Sam's changes. ethereum/EIPs#9151
    *  Will need one more editor's approval.
*  Update EIP-1: Redefine what a meta EIP is ethereum/EIPs#9153 (Draft)
    *  Will be discussed with the Call For Input.

#### Other topics
*  Add EIP: On-chain upgrade signaling ethereum/EIPs#9174 
    *  Author proposing changes to Ethereum mainnet. Proposal is waiting to be merged as `Draft`.
    *  Gajinder: The proposal suggests that the validators on chain would signal when is the time to upgrade. It feels less likely to be added on the mainnet with current specs. It seems under-specified. 
    *  Question - should we discuss the feasibility before merging?
    *  Sam: As editors, we shouldn't be making decisions on the technical viability of the proposal and should merge and give a number. 
    *  Even though the specification can be specified in `Draft` or `Review` status, this particular EIP need specification. As an editor, it is important to evaluate the feasibility of the proposal.
    *  **To Do**: Gajinder will add the comment to specify the missing details in order to merge this proposal. 
*  can we have a tag that we can add to EIP: active consideration to prevent EIPs from being pulled in stagnent?
    *  Even if the Bot's stangnat PR is closed, the EIP is merged as `Stagnant`. 
    *  There are various EIPs that are bounced from one to another upgrade with no change in the EIP. These are in active consideration so it shouldn't be made `Stagnant`. 
    *  **To Do**: Considering this is the case for many Core EIPs, Sam will look into alternatives to stop the Stagnant bot from merging these EIPs. This will be discussed in the next meeting.
     
#### Call for Input
Call For Input	Status	Inclination/Result	Deadline
- **To do**: Editors are invited to add input.

### 2. Other discussions and updates from past meetings
*  Adding EIP Reviewers - permissions, requirements, roles & responsibilities
* Reviewer's [ref. document](https://hackmd.io/@poojaranjan/EIPReviewer)
    * The proposal is to introduce a formal position EIP Reviewers, who would support EIP editing process. 
    * All editors are in favor. 
    * **To do**: to the Editors' workshop.
*  Adding new editors & Onboarding Checklist
    *  **To do**: Add respective PRs to EIP-1 & EIP-5069
*  Announcement - EIP [Editors' Workshop](https://github.com/ethcatherders/EIPIP/issues/372)

### 3. EIPs Insight - Monthly EIPs status reporting.
-  a demo of a new tool "Proposal Builder" was shared. seems like a useful tool for new authors.
- Website: Request to add our proposal builder tool link to eips.ethereum.org ethereum/EIPs#9244
    - **To do**: Editors please take a look and comments 

### Next Meeting date & time - Feb 19, 2025 (3rd Wed of the Month) at 15:00 UTC

**Comment by poojaranjan** [comment]
Closing in favor of #378
